"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import sys
import typing

import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _RevocationReason:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _RevocationReasonEnumTypeWrapper(
    google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[
        _RevocationReason.ValueType
    ],
    builtins.type,
):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UNSPECIFIED: _RevocationReason.ValueType  # 0
    KEY_COMPROMISE: _RevocationReason.ValueType  # 1
    CA_COMPROMISE: _RevocationReason.ValueType  # 2
    AFFILIATION_CHANGED: _RevocationReason.ValueType  # 3
    SUPERSEDED: _RevocationReason.ValueType  # 4
    CESSATION_OF_OPERATION: _RevocationReason.ValueType  # 5
    CERTIFICATE_HOLD: _RevocationReason.ValueType  # 6
    REMOVE_FROM_CRL: _RevocationReason.ValueType  # 8
    PRIVILEGE_WITHDRAWN: _RevocationReason.ValueType  # 9
    AA_COMPROMISE: _RevocationReason.ValueType  # 10

class RevocationReason(
    _RevocationReason, metaclass=_RevocationReasonEnumTypeWrapper
): ...

UNSPECIFIED: RevocationReason.ValueType  # 0
KEY_COMPROMISE: RevocationReason.ValueType  # 1
CA_COMPROMISE: RevocationReason.ValueType  # 2
AFFILIATION_CHANGED: RevocationReason.ValueType  # 3
SUPERSEDED: RevocationReason.ValueType  # 4
CESSATION_OF_OPERATION: RevocationReason.ValueType  # 5
CERTIFICATE_HOLD: RevocationReason.ValueType  # 6
REMOVE_FROM_CRL: RevocationReason.ValueType  # 8
PRIVILEGE_WITHDRAWN: RevocationReason.ValueType  # 9
AA_COMPROMISE: RevocationReason.ValueType  # 10
global___RevocationReason = RevocationReason

@typing.final
class ListIssuersRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___ListIssuersRequest = ListIssuersRequest

@typing.final
class IssuerList(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ISSUERS_FIELD_NUMBER: builtins.int
    @property
    def issuers(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        global___IssuerInfo
    ]: ...
    def __init__(
        self,
        *,
        issuers: collections.abc.Iterable[global___IssuerInfo] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["issuers", b"issuers"]) -> None: ...

global___IssuerList = IssuerList

@typing.final
class CreateIssuerRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IDENTIFIER_FIELD_NUMBER: builtins.int
    CERT_FIELD_NUMBER: builtins.int
    PRIVATE_KEY_FIELD_NUMBER: builtins.int
    N_CLIENT_SECRETS_FIELD_NUMBER: builtins.int
    identifier: builtins.str
    cert: builtins.str
    private_key: builtins.str
    n_client_secrets: builtins.int
    def __init__(
        self,
        *,
        identifier: builtins.str = ...,
        cert: builtins.str = ...,
        private_key: builtins.str = ...,
        n_client_secrets: builtins.int | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "_n_client_secrets",
            b"_n_client_secrets",
            "n_client_secrets",
            b"n_client_secrets",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "_n_client_secrets",
            b"_n_client_secrets",
            "cert",
            b"cert",
            "identifier",
            b"identifier",
            "n_client_secrets",
            b"n_client_secrets",
            "private_key",
            b"private_key",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["_n_client_secrets", b"_n_client_secrets"]
    ) -> typing.Literal["n_client_secrets"] | None: ...

global___CreateIssuerRequest = CreateIssuerRequest

@typing.final
class CreateIssuerResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IDENTIFIER_FIELD_NUMBER: builtins.int
    CERT_FIELD_NUMBER: builtins.int
    CLIENT_SECRETS_FIELD_NUMBER: builtins.int
    identifier: builtins.str
    cert: builtins.str
    @property
    def client_secrets(
        self,
    ) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[
        builtins.str
    ]: ...
    def __init__(
        self,
        *,
        identifier: builtins.str = ...,
        cert: builtins.str = ...,
        client_secrets: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "cert",
            b"cert",
            "client_secrets",
            b"client_secrets",
            "identifier",
            b"identifier",
        ],
    ) -> None: ...

global___CreateIssuerResponse = CreateIssuerResponse

@typing.final
class IssuerInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IDENTIFIER_FIELD_NUMBER: builtins.int
    CERT_FIELD_NUMBER: builtins.int
    identifier: builtins.str
    cert: builtins.str
    """PEM-encoded certificate"""
    def __init__(
        self,
        *,
        identifier: builtins.str = ...,
        cert: builtins.str = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing.Literal["cert", b"cert", "identifier", b"identifier"]
    ) -> None: ...

global___IssuerInfo = IssuerInfo

@typing.final
class RollClientSecretsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ISSUER_FIELD_NUMBER: builtins.int
    SECRET_FIELD_NUMBER: builtins.int
    N_CLIENT_SECRETS_FIELD_NUMBER: builtins.int
    issuer: builtins.str
    secret: builtins.str
    n_client_secrets: builtins.int
    def __init__(
        self,
        *,
        issuer: builtins.str = ...,
        secret: builtins.str = ...,
        n_client_secrets: builtins.int | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "_n_client_secrets",
            b"_n_client_secrets",
            "n_client_secrets",
            b"n_client_secrets",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "_n_client_secrets",
            b"_n_client_secrets",
            "issuer",
            b"issuer",
            "n_client_secrets",
            b"n_client_secrets",
            "secret",
            b"secret",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["_n_client_secrets", b"_n_client_secrets"]
    ) -> typing.Literal["n_client_secrets"] | None: ...

global___RollClientSecretsRequest = RollClientSecretsRequest

@typing.final
class RollClientSecretsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CLIENT_SECRETS_FIELD_NUMBER: builtins.int
    @property
    def client_secrets(
        self,
    ) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[
        builtins.str
    ]: ...
    def __init__(
        self,
        *,
        client_secrets: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing.Literal["client_secrets", b"client_secrets"]
    ) -> None: ...

global___RollClientSecretsResponse = RollClientSecretsResponse

@typing.final
class UpdateCrlRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ISSUER_FIELD_NUMBER: builtins.int
    SECRET_FIELD_NUMBER: builtins.int
    issuer: builtins.str
    secret: builtins.str
    def __init__(
        self,
        *,
        issuer: builtins.str = ...,
        secret: builtins.str = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing.Literal["issuer", b"issuer", "secret", b"secret"]
    ) -> None: ...

global___UpdateCrlRequest = UpdateCrlRequest

@typing.final
class UpdateCrlResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___UpdateCrlResponse = UpdateCrlResponse

@typing.final
class SignCertificateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ISSUER_FIELD_NUMBER: builtins.int
    SECRET_FIELD_NUMBER: builtins.int
    CSR_FIELD_NUMBER: builtins.int
    NOT_BEFORE_FIELD_NUMBER: builtins.int
    NOT_AFTER_FIELD_NUMBER: builtins.int
    issuer: builtins.str
    secret: builtins.str
    csr: builtins.bytes
    """DER-encoded certificate signing request."""
    @property
    def not_before(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def not_after(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        issuer: builtins.str = ...,
        secret: builtins.str = ...,
        csr: builtins.bytes = ...,
        not_before: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        not_after: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "_not_after",
            b"_not_after",
            "_not_before",
            b"_not_before",
            "not_after",
            b"not_after",
            "not_before",
            b"not_before",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "_not_after",
            b"_not_after",
            "_not_before",
            b"_not_before",
            "csr",
            b"csr",
            "issuer",
            b"issuer",
            "not_after",
            b"not_after",
            "not_before",
            b"not_before",
            "secret",
            b"secret",
        ],
    ) -> None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_not_after", b"_not_after"]
    ) -> typing.Literal["not_after"] | None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_not_before", b"_not_before"]
    ) -> typing.Literal["not_before"] | None: ...

global___SignCertificateRequest = SignCertificateRequest

@typing.final
class SignCertificateResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DER_FIELD_NUMBER: builtins.int
    der: builtins.bytes
    def __init__(
        self,
        *,
        der: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["der", b"der"]) -> None: ...

global___SignCertificateResponse = SignCertificateResponse

@typing.final
class RevokeCertificateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ISSUER_FIELD_NUMBER: builtins.int
    SECRET_FIELD_NUMBER: builtins.int
    SERIAL_FIELD_NUMBER: builtins.int
    REASON_FIELD_NUMBER: builtins.int
    issuer: builtins.str
    secret: builtins.str
    serial: builtins.str
    reason: global___RevocationReason.ValueType
    def __init__(
        self,
        *,
        issuer: builtins.str = ...,
        secret: builtins.str = ...,
        serial: builtins.str = ...,
        reason: global___RevocationReason.ValueType | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["_reason", b"_reason", "reason", b"reason"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "_reason",
            b"_reason",
            "issuer",
            b"issuer",
            "reason",
            b"reason",
            "secret",
            b"secret",
            "serial",
            b"serial",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["_reason", b"_reason"]
    ) -> typing.Literal["reason"] | None: ...

global___RevokeCertificateRequest = RevokeCertificateRequest

@typing.final
class RevokeCertificateResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___RevokeCertificateResponse = RevokeCertificateResponse

@typing.final
class ListCertificatesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ISSUER_FIELD_NUMBER: builtins.int
    issuer: builtins.str
    def __init__(
        self,
        *,
        issuer: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["issuer", b"issuer"]) -> None: ...

global___ListCertificatesRequest = ListCertificatesRequest

@typing.final
class ListCertificatesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CERTIFICATES_FIELD_NUMBER: builtins.int
    @property
    def certificates(
        self,
    ) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[
        builtins.str
    ]: ...
    def __init__(
        self,
        *,
        certificates: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing.Literal["certificates", b"certificates"]
    ) -> None: ...

global___ListCertificatesResponse = ListCertificatesResponse
