"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.duration_pb2
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _RevocationReason:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _RevocationReasonEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_RevocationReason.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UNSPECIFIED: _RevocationReason.ValueType  # 0
    KEY_COMPROMISE: _RevocationReason.ValueType  # 1
    CA_COMPROMISE: _RevocationReason.ValueType  # 2
    AFFILIATION_CHANGED: _RevocationReason.ValueType  # 3
    SUPERSEDED: _RevocationReason.ValueType  # 4
    CESSATION_OF_OPERATION: _RevocationReason.ValueType  # 5
    CERTIFICATE_HOLD: _RevocationReason.ValueType  # 6
    REMOVE_FROM_CRL: _RevocationReason.ValueType  # 8
    PRIVILEGE_WITHDRAWN: _RevocationReason.ValueType  # 9
    AA_COMPROMISE: _RevocationReason.ValueType  # 10

class RevocationReason(_RevocationReason, metaclass=_RevocationReasonEnumTypeWrapper): ...

UNSPECIFIED: RevocationReason.ValueType  # 0
KEY_COMPROMISE: RevocationReason.ValueType  # 1
CA_COMPROMISE: RevocationReason.ValueType  # 2
AFFILIATION_CHANGED: RevocationReason.ValueType  # 3
SUPERSEDED: RevocationReason.ValueType  # 4
CESSATION_OF_OPERATION: RevocationReason.ValueType  # 5
CERTIFICATE_HOLD: RevocationReason.ValueType  # 6
REMOVE_FROM_CRL: RevocationReason.ValueType  # 8
PRIVILEGE_WITHDRAWN: RevocationReason.ValueType  # 9
AA_COMPROMISE: RevocationReason.ValueType  # 10
global___RevocationReason = RevocationReason

@typing.final
class ListIssuersRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___ListIssuersRequest = ListIssuersRequest

@typing.final
class IssuerList(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ISSUERS_FIELD_NUMBER: builtins.int
    @property
    def issuers(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___IssuerInfo]: ...
    def __init__(
        self,
        *,
        issuers: collections.abc.Iterable[global___IssuerInfo] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["issuers", b"issuers"]) -> None: ...

global___IssuerList = IssuerList

@typing.final
class CreateIssuerRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IDENTIFIER_FIELD_NUMBER: builtins.int
    CERT_FIELD_NUMBER: builtins.int
    PRIVATE_KEY_FIELD_NUMBER: builtins.int
    N_CLIENT_SECRETS_FIELD_NUMBER: builtins.int
    identifier: builtins.str
    cert: builtins.str
    private_key: builtins.str
    n_client_secrets: builtins.int
    def __init__(
        self,
        *,
        identifier: builtins.str = ...,
        cert: builtins.str = ...,
        private_key: builtins.str = ...,
        n_client_secrets: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_n_client_secrets", b"_n_client_secrets", "n_client_secrets", b"n_client_secrets"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_n_client_secrets", b"_n_client_secrets", "cert", b"cert", "identifier", b"identifier", "n_client_secrets", b"n_client_secrets", "private_key", b"private_key"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_n_client_secrets", b"_n_client_secrets"]) -> typing.Literal["n_client_secrets"] | None: ...

global___CreateIssuerRequest = CreateIssuerRequest

@typing.final
class CreateIssuerResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IDENTIFIER_FIELD_NUMBER: builtins.int
    CERT_FIELD_NUMBER: builtins.int
    CLIENT_SECRETS_FIELD_NUMBER: builtins.int
    identifier: builtins.str
    cert: builtins.str
    @property
    def client_secrets(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        identifier: builtins.str = ...,
        cert: builtins.str = ...,
        client_secrets: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["cert", b"cert", "client_secrets", b"client_secrets", "identifier", b"identifier"]) -> None: ...

global___CreateIssuerResponse = CreateIssuerResponse

@typing.final
class IssuerInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IDENTIFIER_FIELD_NUMBER: builtins.int
    CERT_FIELD_NUMBER: builtins.int
    identifier: builtins.str
    cert: builtins.str
    """PEM-encoded certificate"""
    def __init__(
        self,
        *,
        identifier: builtins.str = ...,
        cert: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["cert", b"cert", "identifier", b"identifier"]) -> None: ...

global___IssuerInfo = IssuerInfo

@typing.final
class RollClientSecretsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ISSUER_FIELD_NUMBER: builtins.int
    SECRET_FIELD_NUMBER: builtins.int
    N_CLIENT_SECRETS_FIELD_NUMBER: builtins.int
    issuer: builtins.str
    secret: builtins.str
    n_client_secrets: builtins.int
    def __init__(
        self,
        *,
        issuer: builtins.str = ...,
        secret: builtins.str = ...,
        n_client_secrets: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_n_client_secrets", b"_n_client_secrets", "n_client_secrets", b"n_client_secrets"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_n_client_secrets", b"_n_client_secrets", "issuer", b"issuer", "n_client_secrets", b"n_client_secrets", "secret", b"secret"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_n_client_secrets", b"_n_client_secrets"]) -> typing.Literal["n_client_secrets"] | None: ...

global___RollClientSecretsRequest = RollClientSecretsRequest

@typing.final
class RollClientSecretsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CLIENT_SECRETS_FIELD_NUMBER: builtins.int
    @property
    def client_secrets(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        client_secrets: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["client_secrets", b"client_secrets"]) -> None: ...

global___RollClientSecretsResponse = RollClientSecretsResponse

@typing.final
class UpdateCrlRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ISSUER_FIELD_NUMBER: builtins.int
    SECRET_FIELD_NUMBER: builtins.int
    issuer: builtins.str
    secret: builtins.str
    def __init__(
        self,
        *,
        issuer: builtins.str = ...,
        secret: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["issuer", b"issuer", "secret", b"secret"]) -> None: ...

global___UpdateCrlRequest = UpdateCrlRequest

@typing.final
class UpdateCrlResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___UpdateCrlResponse = UpdateCrlResponse

@typing.final
class SignCertificateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ISSUER_FIELD_NUMBER: builtins.int
    SECRET_FIELD_NUMBER: builtins.int
    SPKI_FIELD_NUMBER: builtins.int
    DER_FIELD_NUMBER: builtins.int
    COMMON_NAME_FIELD_NUMBER: builtins.int
    NOT_BEFORE_OFFSET_FIELD_NUMBER: builtins.int
    NAF_FIELD_NUMBER: builtins.int
    TTL_FIELD_NUMBER: builtins.int
    issuer: builtins.str
    secret: builtins.str
    spki: builtins.str
    """SubjectPublicKeyInfo in PEM format, useful when you do not have a proper
    CSR but just a public key.
    """
    der: builtins.bytes
    """DER-encoded X.509 certificate signing request."""
    common_name: builtins.str
    @property
    def not_before_offset(self) -> google.protobuf.duration_pb2.Duration:
        """Duration with which to offset the not_before time to account for clock skew.
        Default is -30 seconds, menaing that the certificate's validity period starts
        30 seconds _before_ the time of issuance.
        """

    @property
    def naf(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Standard notAfter time, which is the time at which the certificate expires."""

    @property
    def ttl(self) -> google.protobuf.duration_pb2.Duration:
        """Time to live for the certificate. Must be positive."""

    def __init__(
        self,
        *,
        issuer: builtins.str = ...,
        secret: builtins.str = ...,
        spki: builtins.str = ...,
        der: builtins.bytes = ...,
        common_name: builtins.str | None = ...,
        not_before_offset: google.protobuf.duration_pb2.Duration | None = ...,
        naf: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        ttl: google.protobuf.duration_pb2.Duration | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_common_name", b"_common_name", "_not_before_offset", b"_not_before_offset", "common_name", b"common_name", "csr", b"csr", "der", b"der", "naf", b"naf", "not_after", b"not_after", "not_before_offset", b"not_before_offset", "spki", b"spki", "ttl", b"ttl"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_common_name", b"_common_name", "_not_before_offset", b"_not_before_offset", "common_name", b"common_name", "csr", b"csr", "der", b"der", "issuer", b"issuer", "naf", b"naf", "not_after", b"not_after", "not_before_offset", b"not_before_offset", "secret", b"secret", "spki", b"spki", "ttl", b"ttl"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_common_name", b"_common_name"]) -> typing.Literal["common_name"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_not_before_offset", b"_not_before_offset"]) -> typing.Literal["not_before_offset"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["csr", b"csr"]) -> typing.Literal["spki", "der"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["not_after", b"not_after"]) -> typing.Literal["naf", "ttl"] | None: ...

global___SignCertificateRequest = SignCertificateRequest

@typing.final
class SignCertificateResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DER_FIELD_NUMBER: builtins.int
    der: builtins.bytes
    def __init__(
        self,
        *,
        der: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["der", b"der"]) -> None: ...

global___SignCertificateResponse = SignCertificateResponse

@typing.final
class RevokeCertificateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ISSUER_FIELD_NUMBER: builtins.int
    SECRET_FIELD_NUMBER: builtins.int
    SERIAL_FIELD_NUMBER: builtins.int
    REASON_FIELD_NUMBER: builtins.int
    INVALIDITY_DATE_FIELD_NUMBER: builtins.int
    issuer: builtins.str
    secret: builtins.str
    serial: builtins.str
    reason: global___RevocationReason.ValueType
    @property
    def invalidity_date(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        issuer: builtins.str = ...,
        secret: builtins.str = ...,
        serial: builtins.str = ...,
        reason: global___RevocationReason.ValueType | None = ...,
        invalidity_date: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_invalidity_date", b"_invalidity_date", "_reason", b"_reason", "invalidity_date", b"invalidity_date", "reason", b"reason"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_invalidity_date", b"_invalidity_date", "_reason", b"_reason", "invalidity_date", b"invalidity_date", "issuer", b"issuer", "reason", b"reason", "secret", b"secret", "serial", b"serial"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_invalidity_date", b"_invalidity_date"]) -> typing.Literal["invalidity_date"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_reason", b"_reason"]) -> typing.Literal["reason"] | None: ...

global___RevokeCertificateRequest = RevokeCertificateRequest

@typing.final
class RevokeCertificateResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___RevokeCertificateResponse = RevokeCertificateResponse

@typing.final
class ListCertificatesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ISSUER_FIELD_NUMBER: builtins.int
    issuer: builtins.str
    def __init__(
        self,
        *,
        issuer: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["issuer", b"issuer"]) -> None: ...

global___ListCertificatesRequest = ListCertificatesRequest

@typing.final
class ListCertificatesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CERTIFICATES_FIELD_NUMBER: builtins.int
    @property
    def certificates(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        certificates: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["certificates", b"certificates"]) -> None: ...

global___ListCertificatesResponse = ListCertificatesResponse
