"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ListIssuersRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___ListIssuersRequest = ListIssuersRequest

@typing.final
class IssuerList(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ISSUERS_FIELD_NUMBER: builtins.int
    @property
    def issuers(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___IssuerInfo]: ...
    def __init__(
        self,
        *,
        issuers: collections.abc.Iterable[global___IssuerInfo] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["issuers", b"issuers"]) -> None: ...

global___IssuerList = IssuerList

@typing.final
class CreateIssuerRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IDENTIFIER_FIELD_NUMBER: builtins.int
    CERT_FIELD_NUMBER: builtins.int
    PRIVATE_KEY_FIELD_NUMBER: builtins.int
    N_CLIENT_SECRETS_FIELD_NUMBER: builtins.int
    identifier: builtins.str
    cert: builtins.str
    private_key: builtins.str
    n_client_secrets: builtins.int
    def __init__(
        self,
        *,
        identifier: builtins.str = ...,
        cert: builtins.str = ...,
        private_key: builtins.str = ...,
        n_client_secrets: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_n_client_secrets", b"_n_client_secrets", "n_client_secrets", b"n_client_secrets"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_n_client_secrets", b"_n_client_secrets", "cert", b"cert", "identifier", b"identifier", "n_client_secrets", b"n_client_secrets", "private_key", b"private_key"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_n_client_secrets", b"_n_client_secrets"]) -> typing.Literal["n_client_secrets"] | None: ...

global___CreateIssuerRequest = CreateIssuerRequest

@typing.final
class CreateIssuerResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IDENTIFIER_FIELD_NUMBER: builtins.int
    CERT_FIELD_NUMBER: builtins.int
    CLIENT_SECRETS_FIELD_NUMBER: builtins.int
    identifier: builtins.str
    cert: builtins.str
    @property
    def client_secrets(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        identifier: builtins.str = ...,
        cert: builtins.str = ...,
        client_secrets: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["cert", b"cert", "client_secrets", b"client_secrets", "identifier", b"identifier"]) -> None: ...

global___CreateIssuerResponse = CreateIssuerResponse

@typing.final
class IssuerInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IDENTIFIER_FIELD_NUMBER: builtins.int
    CERT_FIELD_NUMBER: builtins.int
    identifier: builtins.str
    cert: builtins.str
    """PEM-encoded certificate"""
    def __init__(
        self,
        *,
        identifier: builtins.str = ...,
        cert: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["cert", b"cert", "identifier", b"identifier"]) -> None: ...

global___IssuerInfo = IssuerInfo

@typing.final
class RollClientSecretsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ISSUER_FIELD_NUMBER: builtins.int
    SECRET_FIELD_NUMBER: builtins.int
    N_CLIENT_SECRETS_FIELD_NUMBER: builtins.int
    issuer: builtins.str
    secret: builtins.str
    n_client_secrets: builtins.int
    def __init__(
        self,
        *,
        issuer: builtins.str = ...,
        secret: builtins.str = ...,
        n_client_secrets: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_n_client_secrets", b"_n_client_secrets", "n_client_secrets", b"n_client_secrets"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_n_client_secrets", b"_n_client_secrets", "issuer", b"issuer", "n_client_secrets", b"n_client_secrets", "secret", b"secret"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_n_client_secrets", b"_n_client_secrets"]) -> typing.Literal["n_client_secrets"] | None: ...

global___RollClientSecretsRequest = RollClientSecretsRequest

@typing.final
class RollClientSecretsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CLIENT_SECRETS_FIELD_NUMBER: builtins.int
    @property
    def client_secrets(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        client_secrets: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["client_secrets", b"client_secrets"]) -> None: ...

global___RollClientSecretsResponse = RollClientSecretsResponse

@typing.final
class UpdateCrlRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ISSUER_FIELD_NUMBER: builtins.int
    SECRET_FIELD_NUMBER: builtins.int
    issuer: builtins.str
    secret: builtins.str
    def __init__(
        self,
        *,
        issuer: builtins.str = ...,
        secret: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["issuer", b"issuer", "secret", b"secret"]) -> None: ...

global___UpdateCrlRequest = UpdateCrlRequest

@typing.final
class UpdateCrlResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___UpdateCrlResponse = UpdateCrlResponse

@typing.final
class SignCertificateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ISSUER_FIELD_NUMBER: builtins.int
    SPKI_FIELD_NUMBER: builtins.int
    SECRET_FIELD_NUMBER: builtins.int
    issuer: builtins.str
    spki: builtins.bytes
    secret: builtins.str
    def __init__(
        self,
        *,
        issuer: builtins.str = ...,
        spki: builtins.bytes = ...,
        secret: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["issuer", b"issuer", "secret", b"secret", "spki", b"spki"]) -> None: ...

global___SignCertificateRequest = SignCertificateRequest

@typing.final
class SignCertificateResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DER_FIELD_NUMBER: builtins.int
    der: builtins.bytes
    def __init__(
        self,
        *,
        der: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["der", b"der"]) -> None: ...

global___SignCertificateResponse = SignCertificateResponse

@typing.final
class ListCertificatesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ISSUER_FIELD_NUMBER: builtins.int
    issuer: builtins.str
    def __init__(
        self,
        *,
        issuer: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["issuer", b"issuer"]) -> None: ...

global___ListCertificatesRequest = ListCertificatesRequest

@typing.final
class ListCertificatesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CERTIFICATES_FIELD_NUMBER: builtins.int
    @property
    def certificates(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        certificates: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["certificates", b"certificates"]) -> None: ...

global___ListCertificatesResponse = ListCertificatesResponse
