name: Docker Build

on:
  push:
    tags:
      - '*'  # Triggers on any tag

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      packages: write  # Required to push to GHCR
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/safe:${{ github.ref_name }}
